---
AllCops:
  NewCops: enable

# Too picky.
Layout/LineLength:
  Max: 140

# This should truly be on for well documented gems.
Style/Documentation:
  Enabled: false

# Neatly aligned code is too swell.
Layout/SpaceBeforeFirstArg:
  Enabled: false

# Don't mess with RSpec DSL.
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

# Use nested module/class definitions instead of compact style.
# Too high git impact to change this now.
Style/ClassAndModuleChildren:
  Enabled: false

# Avoid contradictory style rules by enforce single quotes.
Style/StringLiterals:
  EnforcedStyle: single_quotes
